apiVersion: v1
kind: Service
metadata:
  labels:
    app: knp-hello-go-app                # that app is under Deployment in default NS
  name: knp-hello-go-deploy-namespace-a
  namespace: namespace-a 
spec:
  ports:
  - nodePort: 30050
    port: 8180
    protocol: TCP
    targetPort: 8180
  selector:
    app: knp-hello-go-app
  type: NodePort
