apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-08-20T14:09:18Z"
  labels:
    app: jenkins
  name: jenkins-uat
  namespace: default
  resourceVersion: "79**21"
  selfLink: /api/v1/namespaces/default/services/jenkins-uat
  uid: e9**fc
spec:
  clusterIP: 10.0.7.42
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32355
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
