apiVersion: v1
kind: Endpoints
metadata:
  name: hello-go
  namespace: default
subsets:
- addresses:
  # that's an address my pod is running on.
  - ip: 10.52.3.12
  ports:
  - name: http
    port: 8180
    protocol: TCP


